### ISSUE TITLE
Issues with buttons from nodes... (was Update Controller, when node buttons are pressed ( e.g. `Seed (rgthree)` ).  )

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#80] opened 2024-10-10 22:19 UTC
Minor issue:

Some nodes have buttons, like the `Seed (rgthree)` node.

- These are working in the Controller, but after pressing a button, I need to move the workflow, for the Controller to be updated. 

- It would also be nice if the button labels were shown on top of the button ( not the Controller's option name area ).

- And the last button, it's not an actual button ! In the rgthree node, it's just displaying the last used seed.
But the seed is also shown in the label area. Can this be fixed ?

I know that the Controller can't possibly support all custom nodes from other extensions. 
But most people interested in having a traditional GUI experience, are also probably using this rgthree node.

![rg31](https://github.com/user-attachments/assets/fd7098f4-6190-46c0-9f48-49c7a212da7c)

**Comment by JorgeR81** [comment] 2024-10-11 22:20
About that rgthree node, I was wrong about that button ! 
Can you also include it ?

When we use random seeds, it displays the seed that was used on the current image.
But it also acts as a button: **we can click it, to make that seed fixed.**

I didn't remember that, because I usually don't use random seeds.
But people will want that feature !

**Comment by chrisgoringe** [comment] 2024-10-12 03:13
If the button is enabled, it will appear. I think this works?

**Comment by JorgeR81** [comment] 2024-10-12 10:23
Here are the current issues related to the `Seed (rgthree)` node, in v0.9.5 ( merged )

**major issue:**
- If an `'Seed (rgthree)'` node is added to the Controller, the buttons will not work when pressed.
They will not work in the controller and they will not work in the node itself.

**minor issue:**
- If the last button does not have a seed yet, it will not show up in the Controller.
Is this the intended behavior ? ( I think is could be OK )

![rg3z2](https://github.com/user-attachments/assets/9c604e38-d208-4487-bfdd-d1ad8376c6b2)

![rg3z1](https://github.com/user-attachments/assets/a9aa81ba-f06b-4845-8b98-2ffa42d81de3)

**Comment by chrisgoringe** [comment] 2024-10-12 11:09
Pushed a fix for the major issue to main.

Minor issue is intended behaviour (the button is disabled on the node; disabled controls don't appear in the controller)

**Closed by chrisgoringe** 2024-10-12 11:09 UTC
Labels: completed on branch

**Comment by JorgeR81** [comment] 2024-10-12 11:15
It's working.
