### ISSUE TITLE
Preview Batch more than 1 View in Gui Request

### ISSUE THREAD

**Issue by boricuapab** [chrisgoringe/cg-controller#379] opened 2024-11-23 06:40 UTC
Hi, when rendering a batch of images more than 1, the preview that is in the cg controller gui only shows the first generated image, would be great to show more than once in the preview when the batch is greater than 1.

Thanks

**Comment by boricuapab** [comment] 2024-11-23 06:44
This controller gui is great by the way, I'm converting all my workflows to use it

**Comment by chrisgoringe** [comment] 2024-11-23 08:27
Thanks. Support for batches is currently being worked on, should be coming soon!

If you are brave, you can switch to the branch by going into the cg-controller subdirectory under custom nodes, and typing 'git pull' then 'git switch 1.5', then reload the webpage (no need to restart comfy).

To switch back, 'git switch main'

**Comment by chrisgoringe** [comment] 2024-11-24 01:44
Duplicate of #289

**Closed by chrisgoringe** 2024-11-24 01:44 UTC
