### ISSUE TITLE
[ Bug ] Controllers "forget" group data, after refreshing the browser

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#288] opened 2024-11-04 21:04 UTC
Normal Controller :

![bz1](https://github.com/user-attachments/assets/2a999edd-1021-48a5-ad4f-7f8b0ea5b622)

---

After refreshing the browser ( or loading the workflow ):

![bz2](https://github.com/user-attachments/assets/3259e4a0-9694-42bb-801a-06376384bd38)

---

If I click the Controller refresh button, it fixes this.

**Comment by LukeG89** [comment] 2024-11-04 21:17
Yes, happens to me as well


https://github.com/user-attachments/assets/364aa9f8-206d-4f43-8a48-0e062e4369d4

**Comment by LukeG89** [comment] 2024-11-04 22:10
Found the cause of the issue: it's the 1.3.32 frontend.
They have modified something in the groups that is causing this issue.

**Comment by JorgeR81** [comment] 2024-11-04 22:28
Yeah, it also broke `use everywhere` ( https://github.com/chrisgoringe/cg-use-everywhere/issues/242 )

**Comment by chrisgoringe** [comment] 2024-11-04 22:54
I'm on 1.3.26 - has 1.3.32 been released to the main Comfy yet?

**Comment by JorgeR81** [comment] 2024-11-04 23:07
`1.3.26 ` ships with ComfyUI
`1.3.32 ` is the latest

**Comment by LukeG89** [comment] 2024-11-04 23:08
> I'm on 1.3.26 - has 1.3.32 been released to the main Comfy yet?

No, they released it today in frontend.
But I think it's a matter of time since 1.3.26 has been released a week ago and they do weekly updates in ComfyUI

**Comment by chrisgoringe** [comment] 2024-11-05 00:01
Should now be fixed on 1.3.26. Now to look at UE....

**Comment by LukeG89** [comment] 2024-11-05 08:13
This is fixed!

**Closed** 2024-11-05 08:31 UTC
Labels: completed on branch
