### ISSUE TITLE
[ Bug ] Groups collect nodes while being dragged ( same as UE bug )

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#347] opened 2024-11-16 02:09 UTC
I'm having this same issue with the Controller.

If I disable the Controller in the Manager, this does not happen.

- https://github.com/chrisgoringe/cg-use-everywhere/issues/175

**Comment by chrisgoringe** [comment] 2024-11-16 02:29
I can't reproduce - but I've added the same extra safeguard that worked for ue

**Comment by JorgeR81** [comment] 2024-11-16 09:51
I updated, but I still have this issue. 

Tested in Chrome and Edge.

It still happens, even when there are no Controllers. 
I can only fix this by disabling it the Manager.

Can you reprocude in this workflow ?  [3pass_test.json](https://github.com/user-attachments/files/17784167/3pass_test.json)

It's missing some nodes, because I just removed the custom ones.
But I can still can reproduce with that.

**Comment by JorgeR81** [comment] 2024-11-16 10:20
I did some more testing.

This seems to be caused by a new Frontend version: `1.3.32 ` ( if the Controller is also enabled ).

This version adds "group nesting" ( https://github.com/Comfy-Org/ComfyUI_frontend/releases/tag/v1.3.32 ).

----

The regular ComfyUI still uses `13.26`

**Comment by LukeG89** [comment] 2024-11-16 10:55
> The regular ComfyUI still uses `1.3.26`

They just updated ComfyUI frontend to 1.3.44

**Comment by chrisgoringe** [comment] 2024-11-16 11:04
Ah, they probably changed the property that used to be called
“selectedGroupBeingDragged” or similar that could be used to not check
group membership while dragging.

Hopefully there is an obvious replacement. That’s likely to break UE as
well…

**Comment by LukeG89** [comment] 2024-11-16 11:48
@chrisgoringe If you need it, this is the PR in Litegraph that introduced group nesting:

- https://github.com/Comfy-Org/litegraph.js/pull/262

**Comment by chrisgoringe** [comment] 2024-11-16 11:58
memo to self - looks like canvas.isDragging might be what's needed

**Comment by chrisgoringe** [comment] 2024-11-17 12:18
still can't reproduce - added some more code that might help!

**Comment by LukeG89** [comment] 2024-11-17 12:29
I don't have the problem of collecting nodes when moving groups


https://github.com/user-attachments/assets/e49f786b-084a-4023-ba2a-c4e2efc90527

**Comment by JorgeR81** [comment] 2024-11-17 12:34
I still have it. 

Can you test in my workflow ( https://github.com/chrisgoringe/cg-controller/issues/347#issuecomment-2480497789 )

It tends to happen in more complex workflows.

**Comment by JorgeR81** [comment] 2024-11-17 12:41
Actually, it happens more if the group has a larger size.

Here, only the larger group will collect nodes.

![g1](https://github.com/user-attachments/assets/8efe0ef8-0ee8-4d75-8082-6bcfcbb2d1f7)

![g2](https://github.com/user-attachments/assets/e897a496-7bf7-4d55-b8b9-9674cf2c96c7)

**Comment by LukeG89** [comment] 2024-11-17 12:44
> Can you test in my workflow ( https://github.com/chrisgoringe/cg-controller/issues/347#issuecomment-2480497789 )
> 
> It tends to happen in more complex workflows.

@JorgeR81 Tested, but seems to work fine (except the corrupted linking warning 😅 )


https://github.com/user-attachments/assets/502bbf08-6f2d-4063-a0f3-4fe3de62145d

**Comment by LukeG89** [comment] 2024-11-17 12:52
I don't have UE installed, could it be the cause?

**Comment by JorgeR81** [comment] 2024-11-17 13:10
> (except the corrupted linking warning 😅 )

That workflow had UE nodes. 

I think this causes some warnings from rgthree ( but if have it disabled ).

**Comment by JorgeR81** [comment] 2024-11-17 13:25
I did some more testing, and now it seems to be fixed !

I "updated all", tried the latest frontend, and I don't see this issue anymore.

**Comment by LukeG89** [comment] 2024-11-17 13:28
Yeah, there are situations in which you collect not only the nodes but also groups (and you can't grab the "nested" group)

I noticed that happens when you move the group right after you grab


https://github.com/user-attachments/assets/9e52100a-dd78-4119-b11a-90cc010ef62f

**Comment by JorgeR81** [comment] 2024-11-17 13:37
> I did some more testing, and now it seems to be fixed !

> I noticed that happens when you move the group right after you grab

Ah, yes. I can reproduce if I try it this way.

I was trying very carefully now, so that's why it seems fixed.

**Comment by chrisgoringe** [comment] 2024-11-17 20:39
Yes there seems to be an issue in which when a group starts moving it isn’t
marked as such for a short period, so the logic of not adding nodes to a
moving group doesn’t work…

**Comment by chrisgoringe** [comment] 2024-11-18 00:44
Reworked it to use what should be a safer method. Try your ninja moves now.

**Comment by JorgeR81** [comment] 2024-11-18 00:53
Yeah, it works really well now !

**Closed** 2024-11-18 00:55 UTC
Labels: completed on branch, believe fixed

**Comment by LukeG89** [comment] 2024-11-18 09:17
Absolutely perfect! 🥷
