### ISSUE TITLE
General discussion thread

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#30] opened 2024-10-04 11:07 UTC
What would be the main advantages for this approach versus editing Group Nodes in a subgraph ?
Could this give more flexibility, in the way the control panel is designed ?

Now I can create a "control panel", as a Group Node and hide the widgets I don't want to see.
The problem is that I can't change hidden settings and I need to convert back to nodes, to add / remove nodes. 

There is already a subgraph extension, but the developer did not have time to work on it in the past couple of months.
https://github.com/vivax3794/ComfyUI-Sub-Nodes

![gnodes](https://github.com/user-attachments/assets/5d9586d6-1062-4495-95c0-63225e538e02)

**Comment by chrisgoringe** [comment] 2024-10-04 11:23
Thanks for the question - it was really helpful having to work out the answer!

What I like about doing it this way is that it sits beside a completely unchanged workflow. So I have the original workflow off to the side, editable without any mucking around. That feels like a sustainable solution as comfy changes, as well as being conceptually accessible.

I'm playing with the idea of different views - you can already turn a set of widgets on or off (using the color brown), so there are two views as is, which isn't trivially done with group nodes. Someone suggested already having two panels based on different colours...

I guess I'm kind of motivated by an MVC pattern here - I'm old fashioned 😀.

I also hate the group node internal code with a burning passion, having spent far too long trying to make the use everywhere nodes work with them! (Though to be fair I haven't looked at it since the move to typescript, maybe it's clean now).

**Comment by JorgeR81** [comment] 2024-10-04 12:43
> Someone suggested already having two panels based on different colours...

Having multiple panels would be very useful !

Perhaps this could be also set via placing the nodes into groups.
Lots of users already have workflows with groups for ControlNet, IPAdapter, Face Detailer, etc. ...
We could have a main panel for the basic workflow, and other panels for extra features.

It would also be nice to have only the widgets I want in each panel.
For instance a ControlNet panel with only `load image` and `strength` widgets.
Maybe these could be set within each node's right click menu ( e.g. `add widget to panel` ).

**Comment by chrisgoringe** [comment] 2024-10-04 13:02
I'm hesitant to add to the complexity with the "add widget" sort of thing - trying to keep a clean MVC idiom - but "red nodes in yellow groups" in one panel and "red nodes in blue groups" might give the desired flexibility (since groups can overlap...)

Trying to learn from my mistakes in UE by not adding things just because I can!

**Comment by chrisgoringe** [comment] 2024-10-04 13:04
Oh, and the way I'm selecting just a subset of widgets is by making them inputs, plugging a primitive in, and colouring the primitive...

**Comment by chrisgoringe** [comment] 2024-10-04 13:06
Thinking about it a bit more... is it multiple panels? Or a single panel with a drop down menu? The menu could be a list of all groups with red nodes in, you just pick the group you want to see.

**Comment by JorgeR81** [comment] 2024-10-04 13:28
> Oh, and the way I'm selecting just a subset of widgets is by making them inputs, plugging a primitive in, and colouring the primitive...

Yes, that could work.
It makes the main workflow more complex, but it gives better visual feedback of the duplicated settings. 

![node](https://github.com/user-attachments/assets/b113ce04-4261-4ad5-ac95-39300f173e92)

**Comment by JorgeR81** [comment] 2024-10-04 13:38
> Thinking about it a bit more... is it multiple panels? Or a single panel with a drop down menu? The menu could be a list of all groups with red nodes in, you just pick the group you want to see.

Yes, that would probably be better.

Using multiple panels, we have the risk of creating a controller panel, that's only slightly less complex than the workflow itself ...

**Comment by chrisgoringe** [comment] 2024-10-04 21:31
Actually, for numbers I use trivial INT and FLOAT nodes to avoid control after generate...

**Comment by chrisgoringe** [comment] 2024-10-05 03:31
Hey, @JorgeR81 , take a look at branch 0.6 . I've implemented the select by group name option. See what you think.

**Comment by JorgeR81** [comment] 2024-10-05 14:26
I tested the new branch.
Everything seems to work well.
I only have a few suggestions for improvements. 

---
But first one small issue. 

I've put the main nodes in a group ( "Text2image" ).
But, strangely, this group did not resize correctly to fit the nodes. 
And then I noticed the Controller panel had an "invisible" node, that was "caught" inside this group. 

I can even right click on it.

![node1](https://github.com/user-attachments/assets/ecf7bbff-a076-4774-b3b1-e2881c1d15a6)

**Comment by JorgeR81** [comment] 2024-10-05 15:25
A nice feature would be to store the field positions, after they are changed. 

When I filter a group ( with the drop down menu ) and then show "All groups" again, the field's position can change.

**Comment by JorgeR81** [comment] 2024-10-05 15:30
Another nice feature would be to have tabs instead of a down list.
This would make it look more like a traditional GUI.

**Comment by JorgeR81** [comment] 2024-10-05 15:32
Another issue / feature would be to support the new top bar menu.

The easier way would be to just move the panel location a bit.

If the location could be "dynamic adjusted" it would be better, because the Top bar can have multiple rows, if many workflow tabs are open. And also the Sidebar can be resided by the user.

![new](https://github.com/user-attachments/assets/915c4cf9-86c1-4a57-83d8-ecafa9b9dcee)

---

But ideally this could be integrated in the sidebar itself !

![m1](https://github.com/user-attachments/assets/e1b61c5a-ef0a-411a-b1cc-c66404ce7111)

**Comment by JorgeR81** [comment] 2024-10-05 15:40
Another "nice to have", would be to drag the fields to change its position, instead of using the arrows.
If possible we could have three vertical dots instead of the arrows, to click there and drag.

**Comment by JorgeR81** [comment] 2024-10-05 15:56
I've found another issue related to the new menu compatibility.

If we have the new menu enabled, and drag  in a workflow with a controller panel, then both the top bar and the old floating menu will be visible.

The old floating menu will show up minimized ( the three white bars ), but it can be expanded and it even seems to work.

![menu](https://github.com/user-attachments/assets/5591fa34-7ef2-4938-995c-46f3d676d390)

**Comment by JorgeR81** [comment] 2024-10-05 21:12
I also tried the sliders, but the settings don't seem to work.

![sliders](https://github.com/user-attachments/assets/5860a0bd-d032-4116-b1b5-1dbabafe1e59)

**Comment by chrisgoringe** [comment] 2024-10-05 21:36
Created #37 #38 #39 and #40 to track these...

**Comment by chrisgoringe** [comment] 2024-10-06 02:17
@JorgeR81 I think the branch now has fixes for everything except the sliders (#40) that I can't reproduce.

**Comment by chrisgoringe** [comment] 2024-10-06 02:17
@JorgeR81 

> Another nice feature would be to have tabs ( or some type of buttons ) instead of a drop down list, for the groups.

Not sure about the space this would take up, especially if the workflow is complicated with a lot of different groups? Open to ideas.

**Comment by JorgeR81** [comment] 2024-10-06 08:46
I've seen GUI's with multiple rows of tabs. People are used to that.

Comfy UI also does this with the workflow tabs.

![tabs](https://github.com/user-attachments/assets/365decbf-c028-4192-80dc-4804c5bfbc50)

**Comment by JorgeR81** [comment] 2024-10-06 10:01
I also noticed the settings to arrange the red nodes.
It's a nice idea and it works well.

But unfortunately, it breaks the node placement in each group. 

![g1](https://github.com/user-attachments/assets/d0dee560-1029-4347-91e7-b73e31c082b1)

**Comment by JorgeR81** [comment] 2024-10-06 10:18
It would be nice to use other colors to select the node ( at least from the default colors ).
And also to be able to select, based on the shape of the node ( instead of the color ).
This way we don't have to change the current color codes he have. 

![c1](https://github.com/user-attachments/assets/79df1d05-031c-4584-a992-9612cce29c74)

![c2](https://github.com/user-attachments/assets/8944065b-bb33-4aa4-a5ad-985fbe7dc3cf)

**Comment by chrisgoringe** [comment] 2024-10-06 10:29
> I also noticed the settings to arrange the red nodes.

No idea what this is or where it comes from - not this node!

**Comment by chrisgoringe** [comment] 2024-10-06 10:30
> It would be nice to use other colors to select the node ( at least from the default colors ). And also to be able to select, based on the shape of the node ( instead of the color ).
> 
> And to include advanced control nodes we could use 2 colors, 2 shapes, or 1 color and 1 shape !
> 
> This way we don't have to change the current color codes he have.

Added as #43

**Comment by chrisgoringe** [comment] 2024-10-06 10:36
I've merged the 0,6 branch into main.

Development will now be on 0.7

**Comment by JorgeR81** [comment] 2024-10-06 10:39
> > I also noticed the settings to arrange the red nodes.
> 
> No idea what this is or where it comes from - not this node!

Ah, OK ! I just noticed these now, next to your settings ... probably another custom node ...

![rc](https://github.com/user-attachments/assets/edcc788d-e26f-4f9c-ae76-8576f57588a3)

**Comment by JorgeR81** [comment] 2024-10-06 21:31
Preview images also work ! 

It would be nice to scale the image, like we can scale the prompt box size.

![prev](https://github.com/user-attachments/assets/019a5cb3-4382-4a68-8a0e-0a73cbccb3fb)

**Comment by JorgeR81** [comment] 2024-10-06 21:57
Loading images also works ( kind of ).
The button works, but we need to update the controller to update the image. 

Also, could it be possible to drag the images, instead of using the button ( like on the node ) ?

![load1](https://github.com/user-attachments/assets/4ae22451-4826-4192-b306-3327ff82f2fc)

**Comment by chrisgoringe** [comment] 2024-10-06 22:50
Added #46 and #47 for image upload (refresh and drag and drop)

**Comment by chrisgoringe** [comment] 2024-10-06 22:52
> It would be nice to scale the image, like we can scale the prompt box size.

It currently scales to the (fixed) width. Are you wanting to be able to make it bigger? Width could be an issue there, to avoid breaking all the formatting :)

**Comment by JorgeR81** [comment] 2024-10-06 23:23
> It currently scales to the (fixed) width. Are you wanting to be able to make it bigger? Width could be an issue there, to avoid breaking all the formatting :)

OK, I see, portrait formats end up bigger.

I would only want to make them smaller ! 
Especially the Load Image one, it does not need to be that big.

We could have a small handle at the bottom right corner, to decrease vertical space for the widget. 
And the image would scale down proportionally. 

![img](https://github.com/user-attachments/assets/a10c6914-b6ce-4831-97d6-621e18b4a892)

**Comment by chrisgoringe** [comment] 2024-10-07 05:59
Added as #52.

I just merged 0.7 into main. 

- Image upload updates the image shown
- Image upload supports drag and drop
- drag and drop reordering, 
- choice of colours, 
- automatic updating.

**Comment by JorgeR81** [comment] 2024-10-07 10:22
I've made some mockups for a more readable color scheme:

What do you think ?

---

- original image

![pnl](https://github.com/user-attachments/assets/29039429-adc6-4ae2-a3a1-f54979e81eb8)

---

- change background color 
- remove dotted lines

![pnl7](https://github.com/user-attachments/assets/46b3de3e-244f-4340-8710-488fc72fe891)


---

- Use 2 tone colors 

![pnl11](https://github.com/user-attachments/assets/dc249ea3-9b7a-41f8-b113-e06f0e71cd7e)



---

Make font more similar to nodes:
- Lower brightness on the font
- Smaller font -- or --  taller space for title text ( not pictured )
- Alight to the left 

![pnl12](https://github.com/user-attachments/assets/25ce8e8e-f0b9-47ec-a61d-1d6966e01920)

**Comment by chrisgoringe** [comment] 2024-10-07 11:51
Added #53  - I like :)

**Comment by JorgeR81** [comment] 2024-10-07 13:20
About the slider issue ( https://github.com/chrisgoringe/cg-controller/issues/40 ), it was my fault ! 
I haven't set this up correctly. 

For the cfg, I used a Primitive node, named "cfg".
So I needed to change the setting accordingly: `cfg:value=20`

Now it works. 

---
A good feature related to this would be to:

**Show sliders only on specific widgets, if all settings are filled.**

For 2 reasons:

- the sliders that don't have a setting, will probably not work well anyways.

- I don't want a slider on some widgets ( eg. "height" and "width" ).

---

![slider1](https://github.com/user-attachments/assets/0cbf14e9-b673-497c-a063-540e7ee964ff)

![cfg](https://github.com/user-attachments/assets/54ddc84a-219d-4643-a88f-bac89a0b95c1)

**Comment by JorgeR81** [comment] 2024-10-07 13:37
Could it be possible to add a specific area for dragging ?

Sometimes when I try to use the slider I accidentally drag the whole widget.

The new queue menu has a 3 dot area, on the left, for this.  

![drag](https://github.com/user-attachments/assets/7f70fff3-9a03-4990-812c-68c5f5451472)

**Comment by JorgeR81** [comment] 2024-10-07 14:35
> I just merged 0.7 into main.
> 
> - Image upload updates the image shown
> - Image upload supports drag and drop
> - drag and drop reordering,
> - choice of colours,
> - automatic updating.

All this works for me, except :

- The controller is not updated when a node's color is changed between "control" and "advanced".

- Drag and drop to upload images only works for images without a workflow ( e.g. JPEG ).
If the image has a workflow, Comfy UI will upload the workflow instead.
And even if the image upload is successful we still see a Comfy UI warning about the image not having any workflow.

**Comment by chrisgoringe** [comment] 2024-10-07 21:09
> Could it be possible to add a specific area for dragging ?
> 
> Sometimes when I try to use the slider I accidentally drag the whole widget.
> 
> The new queue menu has a 3 dot area, on the left, for this.

#55

**Comment by chrisgoringe** [comment] 2024-10-07 21:13
> 
> * The controller is not updated when a node's color is changed between the 2 control colors ( to add or remove a node from the advanced controls ).

#56

> * Drag and drop to upload images only works for images without a workflow ( e.g. JPEG ).
>   If the image has a workflow, Comfy UI will upload the workflow instead.
>   And even if the image upload is successful we still see a Comfy UI warning about the image not having any workflow.

#57 (odd. this was working last night for me... I swear!)

I'm going to close this thread, now, it's getting too long for me to cope with. I've enabled Discussions, and created #58 as a starting point

**Closed by chrisgoringe** 2024-10-07 21:13 UTC
Labels: discussion

**Comment by JorgeR81** [comment] 2024-10-07 21:22
Last post in this thread, just to remind you that in my comment about the slider issue ( https://github.com/chrisgoringe/cg-controller/issues/40 ), I also had a suggestion : 

> A good feature related to this would be to:
> 
> Show sliders only on specific widgets, if all settings are filled.
> 
> For 2 reasons:
> 
> - the sliders that don't have a setting, will probably not work well anyways.
> 
> - I don't want a slider on some widgets ( eg. "height" and "width" ).

**Comment by chrisgoringe** [comment] 2024-10-07 21:33
Yeah, I was thinking about that. 

I've started a discussion thread specifically on sliders - https://github.com/chrisgoringe/cg-controller/discussions/59
